{{- if and .Values.rbac.create (not .Values.rbac.clusterRBAC) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: ""
    suite: pachyderm
  name: pachyderm
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: ""
  kind: Role
  name: pachyderm
subjects:
- kind: ServiceAccount
  name: pachyderm
  namespace: default
{{ end -}}
