# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^pachyderm-\d+\.\d+\.\d+$/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^pachyderm-\d+\.\d+\.\d+$/

jobs:
  build:
    docker:
      - image: tiltdev/circleci-kind:v1.4.0
    resource_class: xlarge
    steps:
      - setup_remote_docker
      - checkout
      - run: with-kind-cluster.sh
            
  publish:
    docker:
      - image: chainlink/chart-releaser:v1.1.1
    steps:
      ## Set CR_Token to GH Token
      ## package repo: cr package pachyderm
      ## create release: cr upload -o pachyderm -r helmchart
      ## cr index -o pachyderm -r helmchart -c https://pachyderm.github.io/helmchart --push
      - add_ssh_keys:
          fingerprints:
            - 3e:5e:ce:88:3a:42:ca:26:5e:90:66:f7:78:60:12:e1
      - run:
          name: Avoid hosts unknown for github
          command: echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
      - run: git config --global user.email buildbot@pachyderm.io
      - run: git config --global user.name buildbot
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_TAG} $CIRCLE_REPOSITORY_URL .
      - run: cr package pachyderm
      - run: cr upload -o pachyderm -r helmchart
      - run: cr index -o pachyderm -r helmchart -c https://pachyderm.github.io/helmchart --push
