apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-traefik
  labels:
    app: traefik
    chart: "traefik-1.68.1"
    release: "release-name"
    heritage: "Tiller"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
      release: release-name
  template:
    metadata:
      labels:
        app: traefik
        chart: "traefik-1.68.1"
        release: "release-name"
        heritage: "Tiller"
    spec:
      serviceAccountName: release-name-traefik
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.7.9
        name: release-name-traefik
        readinessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /ssl
          name: ssl
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: httpn
          containerPort: 8880
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        args:
        - --configfile=/config/traefik.toml

      volumes:
      - name: config
        configMap:
          name: release-name-traefik
      - name: ssl
        secret:
          secretName: release-name-traefik-default-cert
