apiVersion: v1
kind: Secret
metadata:
  name: release-name-traefik-default-cert
  labels:
    app: traefik
    chart: traefik-1.69.1
    release: "release-name"
    heritage: "Tiller"
type: Opaque
data:
  tls.crt: {{ .Values.tlsCrt | quote }}
  tls.key: {{ .Values.tlsKey | quote }}
