apiVersion: v1
kind: Service
metadata:
  name: release-name-traefik
  labels:
    app: traefik
    chart: "traefik-1.68.1"
    release: "release-name"
    heritage: "Tiller"
  annotations:
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.pach.clusterIP }}
  externalTrafficPolicy: Cluster
  selector:
    app: traefik
    release: release-name
  ports:
  - port: 80
    name: http
    targetPort: http
  - port: 443
    name: https
    targetPort: https
